services:
  - type: cron
    name: daily-tasks-bot
    schedule: "0 8 * * 1-5"  # Runs at 08:00 UTC, Mon–Fri
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 daily_summary.py"
