services:
  - type: web
    name: daily-summary-bot
    runtime: python
    region: europe-west4
    plan: free
    buildCommand: pip install -r requirements.txt
    start: python daily_summary.py
    autoDeploy: true

